services:
  beacon:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.beacon.rule: Host(`b.dozzle.dev`)
        traefik.http.services.beacon.loadbalancer.server.port: 4000
        traefik.http.routers.beacon.entrypoints: websecure
        traefik.http.routers.beacon.tls.certresolver: myresolver
    networks:
      - web
      - default
    volumes:
      - /data/beacon:/data
  grafana:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.dashboard.rule: Host(`dashboard.dozzle.dev`)
        traefik.http.services.dashboard.loadbalancer.server.port: 3000
        traefik.http.routers.dashboard.entrypoints: websecure
        traefik.http.routers.dashboard.tls.certresolver: myresolver
    environment:
      - GF_SERVER_ROOT_URL=https://dashboard.dozzle.dev
      - GF_SERVER_DOMAIN=dashboard.dozzle.dev
    networks:
      - web
      - default
networks:
  web:
    external: true
