services:
  timescaledb:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  beacon:
    build:
      context: .
      target: dev
    ports:
      - "4000:4000"
    volumes:
      - .:/build
volumes:
  postgres_data:
